version: "3"

services:
  postgres:
    container_name: "postgres"
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - type: "bind"
        source: ./config
        target: /var/lib/postgresql/data
    restart: always